import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import cn from 'classnames'

const universalSans = localFont({ src: '../fonts/UniversalSansDisplayGX.woff2', variable: '--universal-sans' })
const universalItalic = localFont({
  src: '../fonts/UniversalSansItalicDisplayGX.woff2',
  variable: '--universal-italic',
})

export const metadata: Metadata = {
  title: 'Planner',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(universalSans.variable, universalItalic.variable, 'font-sans')}>{children}</body>
    </html>
  )
}
